global:
  scrape_interval: 15s
  scrape_timeout: 1s
  evaluation_interval: 15s
scrape_configs:
- job_name: dev-push-gateway
  metrics_path: /metrics
  scheme: http
  honor_labels: true
  static_configs:
  - targets: ['prom-pushgateway:9091']
    labels:
      service: 'prom-pushgateway'
- job_name: dev-app
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets: ['app1:8080', "app2:8081"]
    labels:
      service: 'app-service'